/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMiddlePanel: typeof import('./src/components/AppMiddlePanel.vue')['default']
    AppRightPanel: typeof import('./src/components/AppRightPanel.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    FPSMonitor: typeof import('./src/components/FPSMonitor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    SiderBar: typeof import('./src/components/SiderBar.vue')['default']
  }
}
